import { notFound } from "next/navigation";
import { and, eq } from "drizzle-orm";
import { requireUser } from "@/lib/auth";
import { db } from "@/db";
import { backtests } from "@/db/schema";
import { Card, StatCard } from "@/components/ui";
import { EquityChart } from "@/components/charts/EquityChart";
import { fmtPct, fmtUsd, fmtDate } from "@/lib/format";
import type { BacktestMetrics, BacktestTrade } from "@/lib/backtest/engine";

export const dynamic = "force-dynamic";

export default async function BacktestDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await requireUser();
  const rows = await db
    .select()
    .from(backtests)
    .where(and(eq(backtests.id, id), eq(backtests.userId, user.id)))
    .limit(1);
  const backtest = rows[0];
  if (!backtest) notFound();

  const metrics = backtest.metrics as BacktestMetrics;
  const equityCurve = backtest.equityCurve as { time: number; equity: number }[];
  const trades = (backtest.tradesLog as BacktestTrade[]) ?? [];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold">{backtest.name}</h1>
        <p className="text-sm text-slate-400">
          {backtest.symbol} · {backtest.timeframe} · created {fmtDate(backtest.createdAt)}
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard label="Total Return" value={fmtPct(metrics.totalReturnPct)} tone={metrics.totalReturnPct >= 0 ? "positive" : "negative"} />
        <StatCard label="CAGR" value={fmtPct(metrics.cagr)} />
        <StatCard label="Sharpe Ratio" value={metrics.sharpeRatio.toFixed(2)} />
        <StatCard label="Max Drawdown" value={`-${metrics.maxDrawdownPct.toFixed(1)}%`} tone="negative" />
        <StatCard label="Win Rate" value={`${metrics.winRate.toFixed(1)}%`} />
        <StatCard label="Profit Factor" value={Number.isFinite(metrics.profitFactor) ? metrics.profitFactor.toFixed(2) : "∞"} />
        <StatCard label="Total Trades" value={String(metrics.totalTrades)} />
        <StatCard label="Final Equity" value={fmtUsd(metrics.finalEquity)} />
      </div>

      <Card>
        <h2 className="mb-4 text-lg font-semibold">Equity Curve</h2>
        <EquityChart data={equityCurve} />
      </Card>

      <Card>
        <h2 className="mb-4 text-lg font-semibold">Trade Log (last {trades.length})</h2>
        {trades.length === 0 ? (
          <p className="py-4 text-center text-sm text-slate-500">No trades were generated by this backtest.</p>
        ) : (
          <div className="max-h-96 overflow-y-auto">
            <table className="w-full text-left text-sm">
              <thead className="sticky top-0 bg-slate-900">
                <tr className="border-b border-slate-800 text-xs uppercase tracking-wide text-slate-500">
                  <th className="py-2 pr-4">Side</th>
                  <th className="py-2 pr-4">Entry</th>
                  <th className="py-2 pr-4">Exit</th>
                  <th className="py-2 pr-4">PnL</th>
                  <th className="py-2 pr-4">PnL %</th>
                </tr>
              </thead>
              <tbody>
                {trades
                  .slice()
                  .reverse()
                  .map((t, i) => (
                    <tr key={i} className="border-b border-slate-900">
                      <td className="py-1.5 pr-4 uppercase">{t.side}</td>
                      <td className="py-1.5 pr-4 tabular-nums">{t.entryPrice.toFixed(2)}</td>
                      <td className="py-1.5 pr-4 tabular-nums">{t.exitPrice.toFixed(2)}</td>
                      <td className={`py-1.5 pr-4 tabular-nums ${t.pnl >= 0 ? "text-emerald-400" : "text-rose-400"}`}>{fmtUsd(t.pnl)}</td>
                      <td className={`py-1.5 pr-4 tabular-nums ${t.pnlPct >= 0 ? "text-emerald-400" : "text-rose-400"}`}>{fmtPct(t.pnlPct)}</td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
